--- #YAML:1.0
name:               ClearCase-Wrapper
version:            1.18
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Argv:                 1.06
    ClearCase::Argv:      1.06
    ClearCase::ClearPrompt:  1.24
    File::Spec:           0.82
    Getopt::Long:         2.17
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
